server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou-v2?&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: dyh18215153215
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


missyou:
  security:
    jwt-key: 1234567
    token-expired-in: 86400000