
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

missyou:
  api-package: com.lin.missyou.api

server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true


wx:
  appid:
  appsecret:
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code=JSCODE&grant_type=authorization_code


